-- REBOUND application schema for Supabase PostgreSQL.
--
-- Supabase Auth owns auth.users. The application currently persists one row
-- per completed exercise session in public.user_sessions. There are no
-- exercise-event, reminder, profile, or recovery-prediction tables in the
-- current implementation.

create table if not exists public.user_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  exercise_name text not null,
  reps_completed integer not null default 0
    check (reps_completed >= 0),
  accuracy_score numeric(5, 2) not null default 0
    check (accuracy_score between 0 and 100),
  session_date date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists user_sessions_user_created_idx
  on public.user_sessions (user_id, created_at desc);

create index if not exists user_sessions_user_exercise_idx
  on public.user_sessions (user_id, exercise_name);

alter table public.user_sessions enable row level security;

drop policy if exists "Users can read their own sessions"
  on public.user_sessions;
create policy "Users can read their own sessions"
  on public.user_sessions for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own sessions"
  on public.user_sessions;
create policy "Users can insert their own sessions"
  on public.user_sessions for insert
  with check (auth.uid() = user_id);

-- backend/main.py also queries a relation named public.users for an email
-- during progress-report generation. That relation is deployment-specific
-- and is intentionally not created here because this repository does not
-- define or write it.
